### ISSUE TITLE
Formating errors in Closures.adoc.

### ISSUE THREAD

**Issue by dram** [gchiu/rebol.net#1]
It seems that there are some format errors in `Closures.adoc`, [line 25](https://github.com/gchiu/rebol.net/blame/master/docs/Closures.adoc#L25) may read as:

```
add2: func [c d] [[c + d]]
```

[Line 35](https://github.com/gchiu/rebol.net/blame/master/docs/Closures.adoc#L35) may read as:

```
add2: closure [c d] [[c + d]]
```

P.S. Thank you for archiving rebol.net, that helps me a lot.

**Comment by gchiu** [comment]
Github now supports .wiki format so the corresponding Closures.wiki renders correctly.
